

ORDER_STATUS_INIT = "未确认"
ORDER_STATUS_CONFIRMED = "已确认"
ORDER_STATUS_INSPECTING = "商检中"
ORDER_STATUS_INSPECTIED = "已商检"
ORDER_STATUS_DECLARATIONG = "报关中"
ORDER_STATUS_DECLARED = "已报关"
ORDER_STATUS_DECLARANCING = "清关中"
ORDER_STATUS_DECLARANCED = "已清关"